apiVersion: v1
kind: Service
metadata:
  name: issuance-service
  labels:
    app: issuance-service
spec:
  clusterIP: None
  selector:
    app: issuance-service
  ports:
    - port: 3000
      targetPort: 3000
